version: '3.9'

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  database-migrations:
    image: flyway/flyway:10
    env_file:
      - project.env
    depends_on:
      - database
    volumes:
      - ./database-migrations:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate

  server:
    image: denoland/deno:1.46.3
    depends_on:
      - database
      - database-migrations
    volumes:
      - ./server:/app
    working_dir: /app
    command: deno run --allow-net --allow-env app.js
    ports:
      - '8000:8000'

  client:
    image: node:20
    depends_on:
      - server
    volumes:
      - ./client:/app
    working_dir: /app
    command: npm run dev
    ports:
      - '5174:5174'

volumes:
  db-data: